Update set.xml
GeckoTH/arkham-horror pull request #179
Opened 2020-12-18 12:03 UTC by pilunte23

fix clues

2020-12-19 16:02 UTC, ChristopherS requested changes

2020-12-19 16:13 UTC, pilunte23 commented on o8g/Scripts/actions.py
> +                #Filter Dream Diary with wrong subtitle
no , there are 4 "Dream Diary" version with same name but different subtitle , only "DreamDiary" with subtitle "Untranslated" have bonded card.

2020-12-19 16:39 UTC, ChristopherS commented on o8g/Scripts/actions.py
> +                #Filter Dream Diary with wrong subtitle
Ah ok, Then same as the comment below.

2020-12-19 17:07 UTC, pilunte23 commented on o8g/Scripts/actions.py
> +    if "0481911c-f906-40ee-acef-d4ad39c2d767" in listeBonded:
i try with this list

limitedOneBondedCode =[
    ["0481911c-f906-40ee-acef-d4ad39c2d767"],
    ["dc7600e3-a132-42b0-b96b-67ca0cee4aff"]
    ]

and this code 

    for idOne in limitedOneBondedCode:
        if idOne in listBonded:
            notify("{} find".format(idOne))
            listBonded = filter(lambda card: card != idOne, listBonded)
            listBonded.append(idOne) 

But i don't why i go in loop but my condition doesn't work.

2020-12-19 17:09 UTC, ChristopherS commented on o8g/Scripts/actions.py
> +    if "0481911c-f906-40ee-acef-d4ad39c2d767" in listeBonded:
`if idOne in listBonded:`

Your variable is called listeBonded

2020-12-20 10:41 UTC, pilunte23 commented on o8g/Scripts/actions.py
> +    if "0481911c-f906-40ee-acef-d4ad39c2d767" in listeBonded:
no , it's not issue , i rename this variable in all my code
def listBonded(deck):
    mute()
    listBonded = []
    for deckcard in deck:
        for sca, bca , bco in zip(sourceCard, bondedCard, bondedCode):
            if sca == deckcard.Name:
                #Filter Dream Diary with wrong subtitle
                if deckcard.Name == "Dream Diary" and deckcard.Subtitle != "Untranslated":
                    continue              
                listBonded.extend(bco)
    #Remove useless multiple bonded card and add only 1 bonded card
    #Essence of the Dream
    #Pendant of the Queen
    for idOne in limitedOneBondedCode:
        test = idOne
        if test in listBonded:
            notify("{} find".format(test))
            listBonded = filter(lambda card: card != test, listBonded)
            listBonded.append(test)
    return listBonded

2020-12-20 11:41 UTC, pilunte23 commented on o8g/Scripts/actions.py
> +    if "0481911c-f906-40ee-acef-d4ad39c2d767" in listeBonded:
Find error finally ^^!!
it's not 
limitedOneBondedCode =[
["0481911c-f906-40ee-acef-d4ad39c2d767"],
["dc7600e3-a132-42b0-b96b-67ca0cee4aff"]
]

but 
limitedOneBondedCode =[
"0481911c-f906-40ee-acef-d4ad39c2d767",
"dc7600e3-a132-42b0-b96b-67ca0cee4aff"
]

2020-12-21 09:57 UTC, ChristopherS requested changes
I would just request a bit of clean up on the code. Otherwise it looks good so far, assuming it has been tested.

2020-12-21 09:57 UTC, ChristopherS commented on o8g/Scripts/actions.py
> +
two Linebreaks for some reason

2020-12-21 09:57 UTC, ChristopherS commented on o8g/Scripts/bonded.py
> +    #Pendant of the Queen
obsolete comments

2020-12-21 09:57 UTC, ChristopherS commented on o8g/Scripts/bonded.py
> +    return listBonded
No newline at end of file

2020-12-21 10:55 UTC, ChristopherS approved these changes
I'd say this one is good to go.

2020-12-21 18:13 UTC, merged