Fix/token seal
GeckoTH/arkham-horror pull request #233
Opened 2021-11-17 13:27 UTC by pilunte23

2021-11-17 13:28 UTC, pilunte23 commented
fix this issue https://github.com/GeckoTH/arkham-horror/issues/231

2021-11-18 06:56 UTC, pilunte23 commented
I load subtype information in shared pile now
it 's fix for https://github.com/GeckoTH/arkham-horror/issues/212

2021-11-20 09:49 UTC, ChristopherS requested changes
Just some clarification how the chaosbag display is supposed to work.

2021-11-20 09:49 UTC, ChristopherS commented on o8g/Scripts/actions.py
> +    if ((cb.markers[Bless] + b >= 10) and isBless) or ((cb.markers[Curse] + c >= 10) and not isBless):
The idea is, that the numbers on the chaosbag represent the total number of tokens in play. Therefore this shouldn't be necessary.

2021-11-20 09:49 UTC, ChristopherS commented on o8g/Scripts/actions.py
> +            c += 1
At first I thought this shouldn't be needed, but I now realize, that there are a few edge cases, where the number of sealed Blurse Tokens should also be counted. Still this should be part of updateBlessCurse() and the total added to the displayed value on the chaosbag.

2021-11-20 09:49 UTC, ChristopherS commented on o8g/Scripts/actions.py
> +    updateBlessCurse()
The idea, why I didn't add this here was, that sealing a Blurse-Token, doesn't change the number of Blurse-tokens in play. So this update is unnecessary.

2021-11-20 09:49 UTC, ChristopherS commented on o8g/Scripts/actions.py
> +    updateBlessCurse()
Same for this.

2021-11-20 09:49 UTC, ChristopherS requested changes
Just some clarification how the chaosbag display is supposed to work.

2021-12-06 16:57 UTC, merged